import sys
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(BASE_DIR)

from Dimensionality_Reduction import cluster_titles_from_csv as DimensionalityReduction
from Linear_Regression import predict_content_length_from_csv as LinearRegression
from K_means import KMeansTextClustering as Kemeans
from Random_forest import MilitaryTextClassifier as RandomForest


# def RandomForest(): ...
def IsolationForest(): ...
def Apriori(): ...
def PCA(): ...
def GMM(): ...
def AgglomerativeClustering(): ...
def Bayes(): ...
def DecisionTree(): ...
